import Head from "next/head";
import Image from "next/image";
export default function Home() {
  return (
    <div className="h-screen w-screen bg-sky-500">
      <Head>
        <title>stakeh◎use</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col h-full w-full items-center justify-center">
        <div className="mb-4">
          <Image
            src="/images/mini-steak-sol.png"
            height="500"
            width="500"
            alt="steak"
          />
        </div>

        <h1 className="text-7xl font-bold text-center text-yellow-500 tracking-[1em] -mr-20">
          yum.
        </h1>
      </main>
    </div>
  );
}
